name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: build (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          set -euo pipefail
          mkdir -p dist
          VERSION="${GITHUB_REF_NAME#v}"
          BIN="shellrest-go"
          OUT="${BIN}_${GOOS}_${GOARCH}"
          echo "Building ${OUT} (version ${VERSION})"
          go build -ldflags='-s -w' -o "${OUT}" .
          TAR="dist/${OUT}.tar.gz"
          # include setup wizard script as 'sshrest-setup'
          cp -f scripts/sshrest-setup.sh sshrest-setup || true
          chmod +x sshrest-setup || true
          tar -czf "$TAR" "${OUT}" sshrest-setup README.md sshrest.conf || \
            tar -czf "$TAR" "${OUT}" sshrest-setup README.md || \
            tar -czf "$TAR" "${OUT}" sshrest-setup || \
            tar -czf "$TAR" "${OUT}"
          (cd dist && sha256sum "${OUT}.tar.gz" > "${OUT}.tar.gz.sha256")

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: |
            dist/shellrest-go_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
            dist/shellrest-go_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz.sha256
          if-no-files-found: error

  release:
    name: create release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List files
        run: |
          echo "Artifacts:" && ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/shellrest-go_*_*.tar.gz
            dist/**/shellrest-go_*_*.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
